<?php $f3 = \Base::instance() ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="<?php echo $ENCODING; ?>" />
        <title>shorty</title>
        <link rel="stylesheet" 
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
              integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
              crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" 
                integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" 
                crossorigin="anonymous"></script>
        <link rel="stylesheet" href="css/shorty.css">
        <script src="/js/clipboard.min.js"></script>
    </head>
    <body class="text-center">
        
        <div class="container d-flex w-100 h-100 p-3 mx-auto flex-column">
            <header class="masthead mb-auto">
              <div class="inner">
                <h3 class="masthead-brand">shorty</h3>
                <nav class="nav nav-masthead justify-content-center">
                  <a class="nav-link active" href="/">Home</a>
                </nav>
              </div>
            </header>

        <main role="main" class="inner">            

            <?php if (\Base::instance()->get('SESSION.errormsg') != "") : ?>
            <div class="alert alert-danger">
                <i class="glyphicon glyphicon-exclamation-sign"></i><strong> Error</strong><br>
                <?php 
                    echo \Base::instance()->get('SESSION.errormsg');
                    \Base::instance()->clear('SESSION.errormsg');
                ?>
            </div>
            <?php endif ?>          
            
            <?php echo $this->render(Base::instance()->get('content')); ?>
    
        </main>
            
        <footer class="mastfoot mt-auto">
          <div class="inner">
              <p>powered by <a href="https://github.com/tacki/shorty">shorty</a></p>
          </div>
        </footer>            
            
        </div>
    </body>
</html>